/**
 * Copyright (c) 2018-present, A2 Rešitve d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package solutions.a2.cdc.oracle.utils.file;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.time.Instant;
import java.util.Map;
import java.util.Properties;

/**
 * CLI for converting env to properties
 *  
 * @author <a href="mailto:averemee@a2.solutions">Aleksei Veremeev</a>
 */
public class Env2Property {
	public static void main(String[] argv) {
		if ((argv.length != 2 && argv.length != 3) ||
				(argv.length == 3 && !"--append".equals(argv[2]))) {
			System.err.println("Usage:");
			System.err.println("java solutions.a2.cdc.oracle.utils.file.Env2Property PREFIX PROPERTY_FILE");
			System.exit(1);
		}
		final String prefix = argv[0];
		final String fileName = argv[1];
		final Properties props = new Properties();
		if (argv.length == 3) {
			try (InputStream is = new FileInputStream(fileName)) {
				props.load(is);
			} catch (IOException ioe) {
				ioe.printStackTrace();
			}
		}

		final Map<String, String> env = System.getenv();
		env.forEach((variable, value) -> {
			if (variable.startsWith(prefix)) {
				final String property = variable
						.substring(prefix.length())
						.replaceAll("___", "%%%")
						.replaceAll("__", "-")
						.replaceAll("_", ".")
						.replaceAll("%%%", "_")
						.toLowerCase();
				props.put(property, value);
			}
		});

		try(OutputStream fos = new FileOutputStream(fileName);
				PrintWriter pw = new PrintWriter(fos)) {

			final String comment = "# Generated by A2 Env2Property utility " + Instant.now().toString();
			pw.println(comment);
			props.forEach((k, v) -> pw.println(k + "=" + v));
			pw.flush();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			System.exit(1);
		}
	}
}
